DROP TABLE IF EXISTS airport;
DROP TABLE IF EXISTS airplane;



-- Tabloları yeniden oluştur
CREATE TABLE IF NOT EXISTS airport (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name VARCHAR(255) NOT NULL,
                         iata_code VARCHAR(3) NOT NULL UNIQUE,
                         country VARCHAR(255) NOT NULL,
                         city VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS airplane (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          tail_number VARCHAR(255) NOT NULL UNIQUE,
                          airline VARCHAR(255) NOT NULL,
                          model VARCHAR(255) NOT NULL,
                          capacity INT NOT NULL CHECK (capacity < 1000 AND capacity > 0)
);

--TODO: ER DIAGRAM
--kuralları yok v2de düzelt.