CREATE TYPE user_role AS ENUM ('ADMIN', 'PASSENGER');

CREATE TABLE IF NOT EXISTS users (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        first_name VARCHAR(50) NOT NULL,
                        last_name VARCHAR(50) NOT NULL,
                        email VARCHAR(100) NOT NULL UNIQUE,
                        password_hash VARCHAR(255) NOT NULL,
                        role user_role
);


