server:
  port: ${PORT:8080}
spring:
  config:
    import: "optional:file:.env[.properties],optional:file:../.env[.properties]"
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  mail:
    host: ${MAILHOG_HOST:localhost}
    port: ${MAILHOG_SMTP_PORT:1025}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USER}
      password: ${REDIS_PASSWORD}
      timeout: 2000ms
      connect-timeout: 2000ms

  cache:
    type: redis
    redis:
      time-to-live: ${REDIS_TTL:3600000}
      cache-null-values: false

mailhog:
  web:
    host: ${MAILHOG_HOST:localhost}
    port: ${MAILHOG_WEB_PORT:8025}
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
  health:
    redis:
      enabled: true
    db:
      enabled: true